AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 with user data"

Parameters:
  InstanceTypeParameter:
    Description: Select instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.large
    Description: Available options are t2.micro, t2.small, t2.large. Default is t2.micro

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-06878d265978313ca
      UserData:
        Fn::Base64:
          !Sub
            - |
              #!/bin/bash
              apt-get update -y
              apt-get install httpd -y
              mkdir /home/ubuntu/${DirName}
            - {DirName: !Join ['-', [!Ref AWS::StackName, !Ref AWS::Region, 'app' ] ] }
