AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 with user data"

# Upload this template first, and copy the url, and then pass to the main template(3-ec2-main.yaml) as input parameter
Resources:
  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable secure access via http
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 192.168.1.1/32

Outputs:
  ManagementSg:
    Value: !Ref SSHSecurityGroup
  ServiceSg:
    Value: !Ref ServerSecurityGroup