AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 with user data"

Parameters: 
  HostInstanceId: 
    Type: AWS::EC2::Instance::Id
  AvailabilityZone: 
    Type: String

# Upload this template first, and copy the url, and then pass to the main template(3-ec2-main.yaml) as input parameter
Resources:
  # Storage
  DataVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 100
      # `AvailabilityZone` is passed in from the caller.
      AvailabilityZone: !Ref AvailabilityZone

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      # `InstanceId` is passed in from the caller.
      InstanceId: !Ref HostInstanceId
      VolumeId: !Ref DataVolume
      Device: /dev/sdh